# Generated by Django 4.2.22 on 2025-06-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0003_consultation_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Заявку', 'verbose_name_plural': 'Заявки на консультацию'},
        ),
    ]
