# Generated by Django 4.2.22 on 2025-06-27 06:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppHome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('speciality', models.CharField(choices=[('stylist', 'стилист'), ('make-up', 'визажист'), ('manicurist', 'мастер маникюра'), ('barber', 'парикмахер')], max_length=20, verbose_name='Специальность')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж лет')),
                ('experience_monts', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)], verbose_name='Стаж месяцев')),
                ('image', models.ImageField(blank=True, null=True, upload_to='masters_photos/', verbose_name='Фото мастера')),
            ],
            options={
                'verbose_name': 'Мастера',
                'verbose_name_plural': 'Мастера',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название салона')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес салона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='salons/', verbose_name='Фото салона')),
            ],
            options={
                'verbose_name': 'Салон',
                'verbose_name_plural': 'Салоны',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hair_coloring', 'окрашивание волос'), ('hair_styling', 'укладка волос'), ('manicure_сlassic', 'Маникюр классический'), ('pedicure', 'педикюр'), ('nail_extensions', 'наращивание ногтей'), ('daytime_makeup', 'дневной макияж'), ('wedding_makeup', 'свадебный макияж'), ('evening_makeup', 'вечерний макияж')], max_length=100, verbose_name='Услуга')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото салона')),
            ],
            options={
                'verbose_name': 'Услугу',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('date', models.DateField(verbose_name='Дата приёма')),
                ('reception_time', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('18:30', '18:30'), ('19:00', '19:00')], max_length=5, verbose_name='Время приёма')),
                ('status', models.CharField(choices=[('paid', 'оплачено'), ('not_paid', 'не оплачено')], default='not_paid', max_length=20, verbose_name='Оплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заявки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='AppHome.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='AppService.master', verbose_name='Мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_appointments', to='AppService.salon', verbose_name='Салон')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_appointments', to='AppService.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
