# Generated by Django 4.2.22 on 2025-06-25 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('speciality', models.CharField(choices=[('stylist', 'стилист'), ('make-up', 'визажист'), ('manicurist', 'мастер маникюра'), ('barber', 'парикмахер')], max_length=20, verbose_name='Специальность')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж лет')),
                ('experience_monts', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(11)], verbose_name='Стаж месяцев')),
                ('image', models.ImageField(blank=True, null=True, upload_to='masters_photos/', verbose_name='Фото мастера')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
