# Generated by Django 4.2.22 on 2025-06-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название салона')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес салона')),
                ('image', models.ImageField(blank=True, null=True, upload_to='salons/', verbose_name='Фото салона')),
            ],
        ),
        migrations.AlterModelOptions(
            name='master',
            options={'verbose_name': 'Мастера', 'verbose_name_plural': 'Мастера'},
        ),
    ]
