# Generated by Django 4.2.22 on 2025-06-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='group_services',
            field=models.CharField(choices=[('hairdressing_services', 'Парикмахерские услуги'), ('nail_service', 'Ногтевой сервис'), ('makeup', 'Макияж')], default='', max_length=100, verbose_name='Услуга'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
