# Generated by Django 4.2.22 on 2025-06-28 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0002_service_group_services_alter_service_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания услуги'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='update_service',
            field=models.DateField(auto_now=True, verbose_name='Последнее обновление'),
        ),
        migrations.AlterField(
            model_name='service',
            name='group_services',
            field=models.CharField(choices=[('hairdressing_services', 'Парикмахерские услуги'), ('nail_service', 'Ногтевой сервис'), ('makeup', 'Макияж')], max_length=100, verbose_name='Группа услуг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Услуга'),
        ),
    ]
