# Generated by Django 4.2.22 on 2025-06-25 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0002_salon_alter_master_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hair_coloring', 'окрашивание волос'), ('hair_styling', 'укладка волос'), ('manicure_сlassic', 'Маникюр классический'), ('pedicure', 'педикюр'), ('nail_extensions', 'наращивание ногтей'), ('daytime_makeup', 'дневной макияж'), ('wedding_makeup', 'свадебный макияж'), ('evening_makeup', 'вечерний макияж')], max_length=100, verbose_name='Услуга')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото салона')),
            ],
        ),
        migrations.AlterModelOptions(
            name='salon',
            options={'verbose_name': 'Салон', 'verbose_name_plural': 'Салоны'},
        ),
    ]
