# Generated by Django 4.2.22 on 2025-06-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0003_service_alter_salon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
    ]
