# Generated by Django 4.2.22 on 2025-06-26 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0003_service_alter_salon_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('reception_time', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('18:30', '18:30'), ('19:00', '19:00')], max_length=5, verbose_name='Время приёма')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='AppService.master')),
            ],
            options={
                'ordering': ['date', 'reception_time'],
                'unique_together': {('master', 'date', 'reception_time')},
            },
        ),
    ]
