# Generated by Django 4.2.22 on 2025-06-29 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0003_service_created_at_service_update_service_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='experience_monts',
            new_name='experience_months',
        ),
        migrations.AddField(
            model_name='master',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='AppService.salon', verbose_name='Салон'),
        ),
    ]
