# Generated by Django 4.2.22 on 2025-06-26 16:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppHome', '0002_alter_client_options_alter_client_first_name_and_more'),
        ('AppService', '0004_alter_service_options_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('date', models.DateField(verbose_name='Дата приёма')),
                ('reception_time', models.CharField(choices=[('10:00', '10:00'), ('10:30', '10:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('15:00', '15:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('18:30', '18:30'), ('19:00', '19:00')], max_length=5, verbose_name='Время приёма')),
                ('status', models.CharField(choices=[('paid', 'оплачено'), ('not_paid', 'не оплачено')], default='not_paid', max_length=20, verbose_name='Оплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и создания заявки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_appointments', to='AppHome.client', verbose_name='Клиент')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='AppService.master', verbose_name='Мастер')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salon_appointments', to='AppService.salon', verbose_name='Салон')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='AppService.service', verbose_name='Услуга')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
