# Generated by Django 4.2.22 on 2025-06-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0004_rename_experience_monts_master_experience_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(related_name='masters', to='AppService.service', verbose_name='Услуги'),
        ),
    ]
