# Generated by Django 4.2.22 on 2025-06-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0004_alter_service_options'),
        ('AppService', '0005_appointment_delete_schedule'),
    ]

    operations = [
    ]
