# Generated by Django 4.2.22 on 2025-07-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0005_consultationrequest'),
        ('AppService', '0005_master_services'),
    ]

    operations = [
    ]
