# Generated by Django 4.2.22 on 2025-07-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppService', '0006_merge_0005_consultationrequest_0005_master_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='salons',
            field=models.ManyToManyField(related_name='services', to='AppService.salon', verbose_name='Доступно в салонах'),
        ),
    ]
